"""FIX-019 WP-3: Strict validation gate for meter reading uploads.

Reads fingerprint from uploaded templates, validates against registry,
and enforces deterministic matching when strict mode is enabled.
"""
import hashlib
import json
from typing import Optional, Dict, Any, List, Tuple
from datetime import date
from openpyxl import Workbook


def read_fingerprint(wb: Workbook) -> Optional[Dict[str, Any]]:
    """Read the hidden fingerprint sheets (_dt_meta, _dt_roster) from a workbook.
    
    Returns None if sheets are missing or unreadable.
    """
    try:
        if "_dt_meta" not in wb.sheetnames or "_dt_roster" not in wb.sheetnames:
            return None
        
        ws_meta = wb["_dt_meta"]
        ws_roster = wb["_dt_roster"]
        
        # Read _dt_meta key/value pairs
        meta = {}
        for row in ws_meta.iter_rows(min_row=1, values_only=True):
            if row[0] and row[1]:
                meta[str(row[0])] = str(row[1])
        
        # Read _dt_roster
        roster = []
        for i, row in enumerate(ws_roster.iter_rows(min_row=2, values_only=True)):
            if i == 0 and row[0] == "resident_id":
                continue  # skip header
            if row[0]:
                roster.append({
                    "resident_id": str(row[0]) if row[0] else "",
                    "room_number": str(row[1]) if row[1] else "",
                    "bed_code": str(row[2]) if row[2] else "",
                    "full_name": str(row[3]) if row[3] else "",
                })
        
        return {
            "template_id": meta.get("template_id"),
            "template_type": meta.get("template_type"),
            "property_code": meta.get("property_code"),
            "period_start": meta.get("period_start"),
            "period_end": meta.get("period_end"),
            "roster_count": int(meta.get("roster_count", 0)),
            "roster_hash": meta.get("roster_hash"),
            "roster": roster,
        }
    except Exception:
        return None


def validate_template_fingerprint(
    fingerprint: Optional[Dict[str, Any]],
    db_template,  # models.MeterReadingTemplate
    property_code: str,
) -> List[Dict[str, str]]:
    """Validate the uploaded template's fingerprint against the registry.
    
    Returns a list of issues: [{severity, code, message}]
    """
    issues = []
    
    if fingerprint is None:
        issues.append({
            "severity": "error",
            "code": "NOT_GENERATED_TEMPLATE",
            "message": "This file was not generated by the system. Please generate a template from Billing > Generate Template."
        })
        return issues
    
    # Check template exists in registry
    if db_template is None:
        issues.append({
            "severity": "error",
            "code": "NOT_GENERATED_TEMPLATE",
            "message": "Template not found in registry. It may have been deleted or corrupted."
        })
        return issues
    
    # Check property matches
    if fingerprint.get("property_code") != property_code:
        issues.append({
            "severity": "error",
            "code": "PROPERTY_MISMATCH",
            "message": f"Template property ({fingerprint.get('property_code')}) does not match selected property ({property_code})."
        })
    
    # Check roster hash
    roster_json = json.dumps(fingerprint.get("roster", []), sort_keys=True, default=str)
    computed_hash = hashlib.sha256(roster_json.encode()).hexdigest()
    if computed_hash != fingerprint.get("roster_hash"):
        issues.append({
            "severity": "error",
            "code": "ROSTER_TAMPERED",
            "message": "Template roster has been modified. Please regenerate the template."
        })
    
    # Check roster count matches
    if len(fingerprint.get("roster", [])) != db_template.roster_count:
        issues.append({
            "severity": "warning",
            "code": "ROSTER_COUNT_MISMATCH",
            "message": f"Roster count mismatch: file has {len(fingerprint.get('roster', []))}, registry has {db_template.roster_count}."
        })
    
    return issues


def deterministic_match_resident(
    room_number: str,
    bed_code: str,
    roster: List[Dict[str, Any]],
) -> Optional[str]:
    """Match a resident by room+bed from the roster (deterministic, no fuzzy matching).
    
    Returns resident_id or None.
    """
    if not room_number or not bed_code:
        return None
    
    room_norm = room_number.strip().upper()
    bed_norm = bed_code.strip().upper()
    
    for entry in roster:
        entry_room = entry.get("room_number", "").strip().upper()
        entry_bed = entry.get("bed_code", "").strip().upper()
        # Match by room + bed letter (last character of bed_code)
        if entry_room == room_norm and entry_bed and entry_bed[-1] == bed_norm[-1]:
            return entry.get("resident_id")
    
    return None


def check_roster_integrity(
    uploaded_residents: List[Tuple[str, str, str]],  # [(room, bed, name), ...]
    roster: List[Dict[str, Any]],
) -> List[Dict[str, str]]:
    """Check that uploaded residents match the roster (no missing/extra/duplicates).
    
    Returns a list of issues.
    """
    issues = []
    
    # Build roster lookup by room+bed
    roster_lookup = {}
    for entry in roster:
        key = (entry.get("room_number", "").strip().upper(), entry.get("bed_code", "").strip().upper()[-1:] if entry.get("bed_code") else "")
        if key[0] and key[1]:
            roster_lookup[key] = entry
    
    # Check for duplicates in uploaded data
    seen = set()
    for room, bed, name in uploaded_residents:
        key = (room.strip().upper(), bed.strip().upper()[-1:] if bed else "")
        if key in seen:
            issues.append({
                "severity": "error",
                "code": "DUPLICATE_RESIDENT",
                "message": f"Duplicate resident: room {room}, bed {bed} ({name})"
            })
        seen.add(key)
    
    # Check for missing residents (in roster but not in upload)
    uploaded_keys = set((r.strip().upper(), b.strip().upper()[-1:] if b else "") for r, b, _ in uploaded_residents)
    for key, entry in roster_lookup.items():
        if key not in uploaded_keys:
            issues.append({
                "severity": "warning",
                "code": "ROSTER_MISSING",
                "message": f"Resident missing from upload: room {entry.get('room_number')}, bed {entry.get('bed_code')} ({entry.get('full_name')})"
            })
    
    # Check for extra residents (in upload but not in roster)
    for room, bed, name in uploaded_residents:
        key = (room.strip().upper(), bed.strip().upper()[-1:] if bed else "")
        if key not in roster_lookup:
            issues.append({
                "severity": "warning",
                "code": "ROSTER_EXTRA",
                "message": f"Extra resident not in roster: room {room}, bed {bed} ({name})"
            })
    
    return issues
